$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: classy-env
image: mcr.microsoft.com/azureml/minimal-ubuntu18.04-py38-cpu-inference
conda_file: environment_model_azure.yml