name: instagram-topic-classifier-api
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - requests=2.31.0
  - pytest=7.3.1
  - pytest-mock=3.10.0
  - pip:
    - azure-functions==1.15.0
    - pytest-cov==4.0.0
