name: instagram-topic-classifier-api
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy=1.24.3
  - requests=2.31.0
  - pytest=7.3.1
  - pytest-mock=3.10.0
  - flask=2.3.2
  - pip:
    - azure-functions==1.15.0
    - pytest-cov==4.0.0
    - python-dotenv==1.0.0