name: instagram-topic-classifier-model
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy=1.24.3
  - scikit-learn=1.2.2
  - pip:
    - azureml-defaults==1.56.0.post1
    - inference-schema[numpy-support]==1.7
    - joblib==1.2.0
    - azureml-dataset-runtime