name: instagram-topic-classifier-api
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - requests=2.31.0

variables:
  AZURE_DEPLOY: "0"

# Local development dependencies (only included when AZURE_DEPLOY is not 1)
{% if environ.get('AZURE_DEPLOY', '0') != '1' %}
  - pytest=7.3.1
  - pytest-mock=3.10.0
{% endif %}

# Azure Functions dependencies (always included)
  - pip:
    - azure-functions==1.15.0

# Add any Azure-specific dependencies here if needed in the future
{% if environ.get('AZURE_DEPLOY', '0') == '1' %}
  # - pip:
  #   - some-azure-specific-package==1.0.0
{% endif %}
