name: instagram-topic-classifier-model
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy=1.24.3
  - scikit-learn=1.2.2
  - pip:
    - azureml-core==1.50.0
    - azureml-defaults==1.50.0
